import { APP_INFO } from '@/constants/appInfo';

/** About the app — ~500 words for the About screen. */
export const ABOUT_PARAGRAPHS: string[] = [
  `${APP_INFO.appName} is an English learning application built to help learners in India and beyond speak, read, and think more clearly in English. Whether you are preparing for school exams, job interviews, or everyday conversations, the app brings practice tools together in one simple mobile experience. Our goal is to make consistent learning feel achievable — even if you only have ten minutes a day.`,
  `At the heart of ${APP_INFO.appName} is real communication. The Random Chat feature connects you with other learners so you can type in English in a safe, structured environment. Many users tell us that chatting with a partner is less intimidating than speaking in a large classroom, and it builds the habit of forming sentences under gentle pressure. You can skip to a new partner when needed and focus on vocabulary you actually use.`,
  `Structured learning is equally important. My Courses and video lessons guide you through grammar, speaking, pronunciation, and writing topics with clear explanations and downloadable PDF support. Learning games — including quizzes, word scramble, fill-in-the-blanks, and flashcards — turn revision into short, rewarding sessions. Points and the leaderboard motivate you to return daily without making study feel like a chore.`,
  `The Rewards section supports long-term growth through our 100-day vocabulary journey. Each day introduces a new word with pronunciation, definitions, examples, and similar words you can tap to hear aloud. Claim daily points, track your progress on the journey bar, and unlock a completion bonus when you finish all one hundred days. A small indicator on Home and the Rewards tab reminds you when today’s reward is still waiting.`,
  `Ohm Assist on the Support tab answers common questions about login, chat, games, courses, and connection issues. Sign-in uses Gmail and a one-time email code so your account stays simple and secure. Your profile stores basic details such as name, region, and learning level so the experience can feel personal over time.`,
  `We take learner safety seriously. Random chat is intended for English practice, not for sharing personal contact details, money requests, or inappropriate content. Please report harmful behaviour through Contact Us and use the app responsibly. Data such as your Gmail login, profile fields, and learning progress are handled according to our Terms & Conditions and applicable privacy practices described there.`,
  `${APP_INFO.appName} is designed for learners who want practical progress: students, professionals, homemakers, and anyone returning to English after a break. The app is distributed through official channels such as Google Play, and we encourage you to download updates only from trusted sources. We continue to improve content, stability, and features based on feedback from our community. Thank you for choosing ${APP_INFO.appName} — we are glad to be part of your learning journey.`,
];

export const ABOUT_WORD_COUNT = ABOUT_PARAGRAPHS.join(' ').split(/\s+/).filter(Boolean).length;
