export type DailyWordEntry = {
  day: number;
  word: string;
  phonetic: string;
  partOfSpeech: string;
  meaning: string;
  example: string;
  whereUsed: string;
  tenses: string | null;
  synonyms: string[];
};

export const DAILY_WORD_TOTAL_DAYS = 100;

const DAILY_WORDS_ALL: DailyWordEntry[] = [
  {
    day: 1,
    word: 'Achieve',
    phonetic: '/əˈtʃiːv/',
    partOfSpeech: 'verb',
    meaning: 'To successfully reach a goal after effort.',
    example: 'She achieved fluency in six months.',
    whereUsed: 'Goals, work, and learning apps.',
    tenses: 'Present: achieve · Past: achieved · Past participle: achieved',
    synonyms: ['accomplish', 'reach', 'attain'],
  },
  {
    day: 2,
    word: 'Benefit',
    phonetic: '/ˈbenɪfɪt/',
    partOfSpeech: 'noun',
    meaning: 'An advantage or helpful effect.',
    example: 'Daily practice has many benefits.',
    whereUsed: 'Health, jobs, and education discussions.',
    tenses: 'Plural: benefits',
    synonyms: ['advantage', 'gain', 'profit'],
  },
  {
    day: 3,
    word: 'Confident',
    phonetic: '/ˈkɒnfɪdənt/',
    partOfSpeech: 'adjective',
    meaning: 'Feeling sure about your abilities.',
    example: 'He feels confident speaking English.',
    whereUsed: 'Interviews, presentations, and motivation.',
    tenses: 'Comparative: more confident · Superlative: most confident',
    synonyms: ['sure', 'bold', 'self-assured'],
  },
  {
    day: 4,
    word: 'Develop',
    phonetic: '/dɪˈveləp/',
    partOfSpeech: 'verb',
    meaning: 'To grow or improve over time.',
    example: 'They developed strong listening skills.',
    whereUsed: 'Skills, cities, and personal growth.',
    tenses: 'Present: develop · Past: developed · Gerund: developing',
    synonyms: ['grow', 'improve', 'build'],
  },
  {
    day: 5,
    word: 'Effort',
    phonetic: '/ˈefət/',
    partOfSpeech: 'noun',
    meaning: 'Physical or mental energy used to do something.',
    example: 'Learning English requires consistent effort.',
    whereUsed: 'School, sports, and teamwork.',
    tenses: 'Countable: efforts (tries)',
    synonyms: ['attempt', 'work', 'exertion'],
  },
  {
    day: 6,
    word: 'Fluent',
    phonetic: '/ˈfluːənt/',
    partOfSpeech: 'adjective',
    meaning: 'Able to speak a language easily and accurately.',
    example: 'She is fluent in English and Hindi.',
    whereUsed: 'Language learning and job profiles.',
    tenses: 'Noun form: fluency',
    synonyms: ['smooth', 'natural', 'proficient'],
  },
  {
    day: 7,
    word: 'Grateful',
    phonetic: '/ˈɡreɪtfəl/',
    partOfSpeech: 'adjective',
    meaning: 'Feeling thankful for something received.',
    example: 'I am grateful for your help.',
    whereUsed: 'Thank-you messages and daily conversation.',
    tenses: 'Adverb: gratefully',
    synonyms: ['thankful', 'appreciative'],
  },
  {
    day: 8,
    word: 'Improve',
    phonetic: '/ɪmˈpruːv/',
    partOfSpeech: 'verb',
    meaning: 'To become better than before.',
    example: 'Your pronunciation is improving quickly.',
    whereUsed: 'Feedback, coaching, and study.',
    tenses: 'Present: improve · Past: improved',
    synonyms: ['enhance', 'upgrade', 'refine'],
  },
  {
    day: 9,
    word: 'Knowledge',
    phonetic: '/ˈnɒlɪdʒ/',
    partOfSpeech: 'noun',
    meaning: 'Information and understanding gained through learning.',
    example: 'Reading builds knowledge.',
    whereUsed: 'Academic and professional talk.',
    tenses: 'Uncountable noun',
    synonyms: ['understanding', 'wisdom', 'expertise'],
  },
  {
    day: 10,
    word: 'Motivate',
    phonetic: '/ˈməʊtɪveɪt/',
    partOfSpeech: 'verb',
    meaning: 'To encourage someone to take action.',
    example: 'Good teachers motivate their students.',
    whereUsed: 'Coaching, leadership, and goals.',
    tenses: 'Present: motivate · Past: motivated',
    synonyms: ['inspire', 'encourage', 'drive'],
  },
  {
    day: 11,
    word: 'Opportunity',
    phonetic: '/ˌɒpəˈtjuːnəti/',
    partOfSpeech: 'noun',
    meaning: 'A good chance to do something useful.',
    example: 'This app is a great opportunity to practice.',
    whereUsed: 'Career, travel, and networking.',
    tenses: 'Plural: opportunities',
    synonyms: ['chance', 'opening', 'prospect'],
  },
  {
    day: 12,
    word: 'Practice',
    phonetic: '/ˈpræktɪs/',
    partOfSpeech: 'noun / verb',
    meaning: 'Repeated exercise to build skill.',
    example: 'Practice speaking every day.',
    whereUsed: 'Language learning (always).',
    tenses: 'Verb: practice · Past: practiced',
    synonyms: ['rehearse', 'train', 'exercise'],
  },
  {
    day: 13,
    word: 'Respect',
    phonetic: '/rɪˈspekt/',
    partOfSpeech: 'noun / verb',
    meaning: 'Admiration for someone or something.',
    example: 'Show respect in group discussions.',
    whereUsed: 'Culture, workplace, and values.',
    tenses: 'Verb: respect · Past: respected',
    synonyms: ['honor', 'regard', 'esteem'],
  },
  {
    day: 14,
    word: 'Succeed',
    phonetic: '/səkˈsiːd/',
    partOfSpeech: 'verb',
    meaning: 'To achieve the result you wanted.',
    example: 'You will succeed if you stay consistent.',
    whereUsed: 'Goals and encouragement.',
    tenses: 'Present: succeed · Past: succeeded',
    synonyms: ['triumph', 'win', 'accomplish'],
  },
  {
    day: 15,
    word: 'Understand',
    phonetic: '/ˌʌndəˈstænd/',
    partOfSpeech: 'verb',
    meaning: 'To know the meaning of something.',
    example: 'I understand the lesson now.',
    whereUsed: 'Classroom and chat (very common).',
    tenses: 'Present: understand · Past: understood',
    synonyms: ['comprehend', 'grasp', 'follow'],
  },
  {
    day: 16,
    word: 'Adapt',
    phonetic: '/əˈdæpt/',
    partOfSpeech: 'verb',
    meaning: 'To change to fit new conditions.',
    example: 'Learners adapt to new accents quickly.',
    whereUsed: 'Travel, work abroad, and culture.',
    tenses: 'Present: adapt · Past: adapted',
    synonyms: ['adjust', 'modify', 'accommodate'],
  },
  {
    day: 17,
    word: 'Brave',
    phonetic: '/breɪv/',
    partOfSpeech: 'adjective',
    meaning: 'Ready to face difficulty or danger.',
    example: 'It is brave to speak a new language publicly.',
    whereUsed: 'Stories, compliments, and challenges.',
    tenses: 'Noun: bravery',
    synonyms: ['courageous', 'bold', 'fearless'],
  },
  {
    day: 18,
    word: 'Challenge',
    phonetic: '/ˈtʃælɪndʒ/',
    partOfSpeech: 'noun',
    meaning: 'Something difficult that tests ability.',
    example: 'Grammar is a fun challenge.',
    whereUsed: 'Games, fitness, and learning.',
    tenses: 'Verb: challenge · Past: challenged',
    synonyms: ['difficulty', 'test', 'obstacle'],
  },
  {
    day: 19,
    word: 'Decide',
    phonetic: '/dɪˈsaɪd/',
    partOfSpeech: 'verb',
    meaning: 'To make a choice after thinking.',
    example: 'They decided to join the English club.',
    whereUsed: 'Plans and daily choices.',
    tenses: 'Present: decide · Past: decided',
    synonyms: ['choose', 'determine', 'resolve'],
  },
  {
    day: 20,
    word: 'Encourage',
    phonetic: '/ɪnˈkʌrɪdʒ/',
    partOfSpeech: 'verb',
    meaning: 'To give support or confidence.',
    example: 'Friends encourage each other to speak.',
    whereUsed: 'Teaching, parenting, and teams.',
    tenses: 'Present: encourage · Past: encouraged',
    synonyms: ['support', 'inspire', 'cheer on'],
  },
  {
    day: 21,
    word: 'Focus',
    phonetic: '/ˈfəʊkəs/',
    partOfSpeech: 'verb / noun',
    meaning: 'To concentrate attention on one thing.',
    example: 'Focus on one new word each day.',
    whereUsed: 'Study tips and productivity.',
    tenses: 'Present: focus · Past: focused',
    synonyms: ['concentrate', 'center', 'attend'],
  },
  {
    day: 22,
    word: 'Generous',
    phonetic: '/ˈdʒenərəs/',
    partOfSpeech: 'adjective',
    meaning: 'Willing to give more than expected.',
    example: 'She is generous with her time.',
    whereUsed: 'Character and compliments.',
    tenses: 'Adverb: generously',
    synonyms: ['kind', 'giving', 'charitable'],
  },
  {
    day: 23,
    word: 'Honest',
    phonetic: '/ˈɒnɪst/',
    partOfSpeech: 'adjective',
    meaning: 'Telling the truth and not cheating.',
    example: 'Be honest about your English level.',
    whereUsed: 'Trust and feedback.',
    tenses: 'Noun: honesty',
    synonyms: ['truthful', 'sincere', 'fair'],
  },
  {
    day: 24,
    word: 'Imagine',
    phonetic: '/ɪˈmædʒɪn/',
    partOfSpeech: 'verb',
    meaning: 'To form a picture or idea in the mind.',
    example: 'Imagine yourself speaking fluently.',
    whereUsed: 'Creativity and motivation.',
    tenses: 'Present: imagine · Past: imagined',
    synonyms: ['picture', 'visualize', 'suppose'],
  },
  {
    day: 25,
    word: 'Journey',
    phonetic: '/ˈdʒɜːni/',
    partOfSpeech: 'noun',
    meaning: 'The process of traveling or growing over time.',
    example: 'Language learning is a long journey.',
    whereUsed: 'Motivation posts and stories.',
    tenses: 'Plural: journeys',
    synonyms: ['trip', 'path', 'adventure'],
  },
  {
    day: 26,
    word: 'Kind',
    phonetic: '/kaɪnd/',
    partOfSpeech: 'adjective',
    meaning: 'Friendly, caring, and helpful.',
    example: 'Kind classmates make practice easier.',
    whereUsed: 'Describing people and actions.',
    tenses: 'Noun: kindness',
    synonyms: ['nice', 'gentle', 'caring'],
  },
  {
    day: 27,
    word: 'Listen',
    phonetic: '/ˈlɪsən/',
    partOfSpeech: 'verb',
    meaning: 'To pay attention to sounds or speech.',
    example: 'Listen carefully before you reply.',
    whereUsed: 'Conversation skills (essential).',
    tenses: 'Present: listen · Past: listened',
    synonyms: ['hear', 'attend', 'heed'],
  },
  {
    day: 28,
    word: 'Memorable',
    phonetic: '/ˈmemərəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Easy to remember for a long time.',
    example: 'Our first chat was memorable.',
    whereUsed: 'Stories and travel.',
    tenses: 'Verb base: remember',
    synonyms: ['unforgettable', 'notable', 'striking'],
  },
  {
    day: 29,
    word: 'Negotiate',
    phonetic: '/nɪˈɡəʊʃieɪt/',
    partOfSpeech: 'verb',
    meaning: 'To discuss terms to reach agreement.',
    example: 'They negotiated a fair price.',
    whereUsed: 'Business and conflict resolution.',
    tenses: 'Present: negotiate · Past: negotiated',
    synonyms: ['bargain', 'discuss', 'arrange'],
  },
  {
    day: 30,
    word: 'Observe',
    phonetic: '/əbˈzɜːv/',
    partOfSpeech: 'verb',
    meaning: 'To watch carefully to learn.',
    example: 'Observe how native speakers link words.',
    whereUsed: 'Science, manners, and learning.',
    tenses: 'Present: observe · Past: observed',
    synonyms: ['watch', 'notice', 'monitor'],
  },
  {
    day: 31,
    word: 'Patient',
    phonetic: '/ˈpeɪʃənt/',
    partOfSpeech: 'adjective',
    meaning: 'Able to wait calmly without anger.',
    example: 'Be patient with your mistakes.',
    whereUsed: 'Learning advice and personality.',
    tenses: 'Noun: patience',
    synonyms: ['calm', 'tolerant', 'understanding'],
  },
  {
    day: 32,
    word: 'Question',
    phonetic: '/ˈkwestʃən/',
    partOfSpeech: 'noun',
    meaning: 'A sentence asked to get information.',
    example: 'Ask one clear question at a time.',
    whereUsed: 'Classroom and support chat.',
    tenses: 'Verb: question · Past: questioned',
    synonyms: ['inquiry', 'query', 'doubt'],
  },
  {
    day: 33,
    word: 'Reliable',
    phonetic: '/rɪˈlaɪəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Able to be trusted to work well.',
    example: 'A reliable app helps daily study.',
    whereUsed: 'Products, people, and services.',
    tenses: 'Opposite: unreliable',
    synonyms: ['dependable', 'trustworthy', 'solid'],
  },
  {
    day: 34,
    word: 'Suggest',
    phonetic: '/səˈdʒest/',
    partOfSpeech: 'verb',
    meaning: 'To propose an idea for others to consider.',
    example: 'I suggest practicing ten minutes daily.',
    whereUsed: 'Advice and planning.',
    tenses: 'Present: suggest · Past: suggested',
    synonyms: ['recommend', 'propose', 'advise'],
  },
  {
    day: 35,
    word: 'Talented',
    phonetic: '/ˈtæləntɪd/',
    partOfSpeech: 'adjective',
    meaning: 'Having a natural ability.',
    example: 'She is a talented speaker.',
    whereUsed: 'Arts, sports, and praise.',
    tenses: 'Noun: talent',
    synonyms: ['gifted', 'skilled', 'able'],
  },
  {
    day: 36,
    word: 'Unique',
    phonetic: '/juˈniːk/',
    partOfSpeech: 'adjective',
    meaning: 'One of a kind; not like others.',
    example: 'Every learner has a unique accent story.',
    whereUsed: 'Marketing and descriptions.',
    tenses: 'Adverb: uniquely',
    synonyms: ['special', 'distinct', 'rare'],
  },
  {
    day: 37,
    word: 'Valuable',
    phonetic: '/ˈvæljuəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Worth a lot; very useful.',
    example: 'Feedback is valuable for improvement.',
    whereUsed: 'Business and learning.',
    tenses: 'Noun: value',
    synonyms: ['precious', 'useful', 'important'],
  },
  {
    day: 38,
    word: 'Wonder',
    phonetic: '/ˈwʌndə/',
    partOfSpeech: 'verb',
    meaning: 'To think curiously or feel surprise.',
    example: 'I wonder how this word is used.',
    whereUsed: 'Questions and reflection.',
    tenses: 'Present: wonder · Past: wondered',
    synonyms: ['question', 'ponder', 'marvel'],
  },
  {
    day: 39,
    word: 'Xenial',
    phonetic: '/ˈziːniəl/',
    partOfSpeech: 'adjective',
    meaning: 'Friendly and hospitable to guests.',
    example: 'A xenial host makes learners comfortable.',
    whereUsed: 'Culture and advanced vocabulary.',
    tenses: 'Related: hospitality',
    synonyms: ['hospitable', 'welcoming', 'cordial'],
  },
  {
    day: 40,
    word: 'Yearn',
    phonetic: '/jɜːn/',
    partOfSpeech: 'verb',
    meaning: 'To want something strongly.',
    example: 'Many yearn to speak English fluently.',
    whereUsed: 'Poetic or formal speech.',
    tenses: 'Present: yearn · Past: yearned',
    synonyms: ['long', 'desire', 'crave'],
  },
  {
    day: 41,
    word: 'Zealous',
    phonetic: '/ˈzeləs/',
    partOfSpeech: 'adjective',
    meaning: 'Showing great energy and enthusiasm.',
    example: 'Zealous students practice every day.',
    whereUsed: 'Formal writing and speeches.',
    tenses: 'Noun: zeal',
    synonyms: ['enthusiastic', 'passionate', 'eager'],
  },
  {
    day: 42,
    word: 'Abandon',
    phonetic: '/əˈbændən/',
    partOfSpeech: 'verb',
    meaning: 'To leave something completely.',
    example: 'Do not abandon your study routine.',
    whereUsed: 'Stories and warnings.',
    tenses: 'Present: abandon · Past: abandoned',
    synonyms: ['leave', 'quit', 'desert'],
  },
  {
    day: 43,
    word: 'Brilliant',
    phonetic: '/ˈbrɪliənt/',
    partOfSpeech: 'adjective',
    meaning: 'Extremely clever or impressive.',
    example: 'That was a brilliant answer.',
    whereUsed: 'Compliments and reviews.',
    tenses: 'Adverb: brilliantly',
    synonyms: ['bright', 'excellent', 'genius'],
  },
  {
    day: 44,
    word: 'Clarify',
    phonetic: '/ˈklærɪfaɪ/',
    partOfSpeech: 'verb',
    meaning: 'To make something easier to understand.',
    example: 'Could you clarify this word?',
    whereUsed: 'Meetings and classroom.',
    tenses: 'Present: clarify · Past: clarified',
    synonyms: ['explain', 'clear up', 'simplify'],
  },
  {
    day: 45,
    word: 'Delicate',
    phonetic: '/ˈdelɪkət/',
    partOfSpeech: 'adjective',
    meaning: 'Easily damaged; needing careful handling.',
    example: 'Pronunciation is a delicate skill.',
    whereUsed: 'Art, health, and manners.',
    tenses: 'Adverb: delicately',
    synonyms: ['fragile', 'subtle', 'sensitive'],
  },
  {
    day: 46,
    word: 'Eager',
    phonetic: '/ˈiːɡə/',
    partOfSpeech: 'adjective',
    meaning: 'Wanting to do something very much.',
    example: 'Learners are eager to try random chat.',
    whereUsed: 'Motivation and introductions.',
    tenses: 'Noun: eagerness',
    synonyms: ['excited', 'keen', 'enthusiastic'],
  },
  {
    day: 47,
    word: 'Faithful',
    phonetic: '/ˈfeɪθfəl/',
    partOfSpeech: 'adjective',
    meaning: 'Loyal and steady over time.',
    example: 'Stay faithful to daily word practice.',
    whereUsed: 'Relationships and habits.',
    tenses: 'Noun: faithfulness',
    synonyms: ['loyal', 'devoted', 'constant'],
  },
  {
    day: 48,
    word: 'Genuine',
    phonetic: '/ˈdʒenjuɪn/',
    partOfSpeech: 'adjective',
    meaning: 'Real and sincere, not fake.',
    example: 'She gave genuine feedback.',
    whereUsed: 'Trust and friendship.',
    tenses: 'Adverb: genuinely',
    synonyms: ['authentic', 'real', 'honest'],
  },
  {
    day: 49,
    word: 'Hesitate',
    phonetic: '/ˈhezɪteɪt/',
    partOfSpeech: 'verb',
    meaning: 'To pause before doing or saying something.',
    example: 'Do not hesitate to ask questions.',
    whereUsed: 'Speaking confidence tips.',
    tenses: 'Present: hesitate · Past: hesitated',
    synonyms: ['pause', 'delay', 'waver'],
  },
  {
    day: 50,
    word: 'Inspire',
    phonetic: '/ɪnˈspaɪə/',
    partOfSpeech: 'verb',
    meaning: 'To fill someone with motivation.',
    example: 'Great mentors inspire learners.',
    whereUsed: 'Speeches and social posts.',
    tenses: 'Present: inspire · Past: inspired',
    synonyms: ['motivate', 'encourage', 'uplift'],
  },
  {
    day: 51,
    word: 'Justify',
    phonetic: '/ˈdʒʌstɪfaɪ/',
    partOfSpeech: 'verb',
    meaning: 'To give a good reason for something.',
    example: 'Can you justify your answer?',
    whereUsed: 'Debates and writing.',
    tenses: 'Present: justify · Past: justified',
    synonyms: ['explain', 'defend', 'support'],
  },
  {
    day: 52,
    word: 'Keen',
    phonetic: '/kiːn/',
    partOfSpeech: 'adjective',
    meaning: 'Very interested or eager.',
    example: 'He is keen to join group discussion.',
    whereUsed: 'British English (very common).',
    tenses: 'Adverb: keenly',
    synonyms: ['eager', 'enthusiastic', 'sharp'],
  },
  {
    day: 53,
    word: 'Loyal',
    phonetic: '/ˈlɔɪəl/',
    partOfSpeech: 'adjective',
    meaning: 'Strongly supporting someone or something.',
    example: 'Loyal friends practice together.',
    whereUsed: 'Friendship and brands.',
    tenses: 'Noun: loyalty',
    synonyms: ['faithful', 'devoted', 'steadfast'],
  },
  {
    day: 54,
    word: 'Modest',
    phonetic: '/ˈmɒdɪst/',
    partOfSpeech: 'adjective',
    meaning: 'Not boasting; humble about ability.',
    example: 'She is modest about her English level.',
    whereUsed: 'Personality and culture.',
    tenses: 'Noun: modesty',
    synonyms: ['humble', 'unassuming'],
  },
  {
    day: 55,
    word: 'Nurture',
    phonetic: '/ˈnɜːtʃə/',
    partOfSpeech: 'verb',
    meaning: 'To help something develop and grow.',
    example: 'Nurture your vocabulary every day.',
    whereUsed: 'Parenting, coaching, and growth.',
    tenses: 'Present: nurture · Past: nurtured',
    synonyms: ['foster', 'support', 'cultivate'],
  },
  {
    day: 56,
    word: 'Optimistic',
    phonetic: '/ˌɒptɪˈmɪstɪk/',
    partOfSpeech: 'adjective',
    meaning: 'Expecting good results in the future.',
    example: 'Stay optimistic about your progress.',
    whereUsed: 'Motivation and mindset.',
    tenses: 'Opposite: pessimistic',
    synonyms: ['hopeful', 'positive', 'confident'],
  },
  {
    day: 57,
    word: 'Persist',
    phonetic: '/pəˈsɪst/',
    partOfSpeech: 'verb',
    meaning: 'To continue despite difficulty.',
    example: 'Persist for 100 days of words.',
    whereUsed: 'Goals and discipline.',
    tenses: 'Present: persist · Past: persisted',
    synonyms: ['continue', 'persevere', 'keep going'],
  },
  {
    day: 58,
    word: 'Qualify',
    phonetic: '/ˈkwɒlɪfaɪ/',
    partOfSpeech: 'verb',
    meaning: 'To meet conditions needed for something.',
    example: 'She qualified for the advanced class.',
    whereUsed: 'Jobs, sports, and exams.',
    tenses: 'Present: qualify · Past: qualified',
    synonyms: ['certify', 'pass'],
  },
  {
    day: 59,
    word: 'Remarkable',
    phonetic: '/rɪˈmɑːkəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Unusual and impressive.',
    example: 'Your improvement is remarkable.',
    whereUsed: 'Praise and news.',
    tenses: 'Adverb: remarkably',
    synonyms: ['extraordinary', 'notable', 'striking'],
  },
  {
    day: 60,
    word: 'Strive',
    phonetic: '/straɪv/',
    partOfSpeech: 'verb',
    meaning: 'To try very hard to achieve something.',
    example: 'Strive for clear communication.',
    whereUsed: 'Formal goals and essays.',
    tenses: 'Present: strive · Past: strove / strived',
    synonyms: ['try', 'aim', 'endeavor'],
  },
  {
    day: 61,
    word: 'Thorough',
    phonetic: '/ˈθʌrə/',
    partOfSpeech: 'adjective',
    meaning: 'Complete with attention to every detail.',
    example: 'Do a thorough review of tenses.',
    whereUsed: 'Work, study, and checks.',
    tenses: 'Adverb: thoroughly',
    synonyms: ['complete', 'detailed', 'full'],
  },
  {
    day: 62,
    word: 'Urgent',
    phonetic: '/ˈɜːdʒənt/',
    partOfSpeech: 'adjective',
    meaning: 'Needing immediate action.',
    example: 'This deadline is urgent.',
    whereUsed: 'Emails and workplace.',
    tenses: 'Noun: urgency',
    synonyms: ['pressing', 'critical', 'immediate'],
  },
  {
    day: 63,
    word: 'Vivid',
    phonetic: '/ˈvɪvɪd/',
    partOfSpeech: 'adjective',
    meaning: 'Producing clear, powerful images in the mind.',
    example: 'Use vivid examples in conversation.',
    whereUsed: 'Writing and storytelling.',
    tenses: 'Adverb: vividly',
    synonyms: ['clear', 'bright', 'graphic'],
  },
  {
    day: 64,
    word: 'Withdraw',
    phonetic: '/wɪðˈdrɔː/',
    partOfSpeech: 'verb',
    meaning: 'To remove or take back.',
    example: 'Do not withdraw from speaking practice.',
    whereUsed: 'Formal and banking contexts.',
    tenses: 'Present: withdraw · Past: withdrew',
    synonyms: ['remove', 'retreat', 'pull back'],
  },
  {
    day: 65,
    word: 'Yield',
    phonetic: '/jiːld/',
    partOfSpeech: 'verb',
    meaning: 'To produce or give way.',
    example: 'Daily study yields strong results.',
    whereUsed: 'Formal writing and traffic signs.',
    tenses: 'Present: yield · Past: yielded',
    synonyms: ['produce', 'generate', 'surrender'],
  },
  {
    day: 66,
    word: 'Ambition',
    phonetic: '/æmˈbɪʃən/',
    partOfSpeech: 'noun',
    meaning: 'A strong desire to achieve success.',
    example: 'Her ambition is to study abroad.',
    whereUsed: 'Career talks and introductions.',
    tenses: 'Plural: ambitions',
    synonyms: ['goal', 'drive', 'aspiration'],
  },
  {
    day: 67,
    word: 'Bargain',
    phonetic: '/ˈbɑːɡɪn/',
    partOfSpeech: 'noun / verb',
    meaning: 'Something bought at a good price; to negotiate.',
    example: 'That course is a real bargain.',
    whereUsed: 'Shopping and markets.',
    tenses: 'Past: bargained',
    synonyms: ['deal', 'discount', 'negotiate'],
  },
  {
    day: 68,
    word: 'Compromise',
    phonetic: '/ˈkɒmprəmaɪz/',
    partOfSpeech: 'noun / verb',
    meaning: 'An agreement where each side gives up something.',
    example: 'They reached a compromise.',
    whereUsed: 'Teamwork and politics.',
    tenses: 'Past: compromised',
    synonyms: ['settlement', 'deal', 'middle ground'],
  },
  {
    day: 69,
    word: 'Dedicate',
    phonetic: '/ˈdedɪkeɪt/',
    partOfSpeech: 'verb',
    meaning: 'To give time and effort to something important.',
    example: 'Dedicate fifteen minutes to listening.',
    whereUsed: 'Goals and habits.',
    tenses: 'Past: dedicated',
    synonyms: ['commit', 'devote', 'assign'],
  },
  {
    day: 70,
    word: 'Embrace',
    phonetic: '/ɪmˈbreɪs/',
    partOfSpeech: 'verb',
    meaning: 'To accept willingly and enthusiastically.',
    example: 'Embrace mistakes as part of learning.',
    whereUsed: 'Motivation and change.',
    tenses: 'Past: embraced',
    synonyms: ['accept', 'welcome', 'adopt'],
  },
  {
    day: 71,
    word: 'Fragile',
    phonetic: '/ˈfrædʒaɪl/',
    partOfSpeech: 'adjective',
    meaning: 'Easy to break or damage.',
    example: 'Confidence can feel fragile at first.',
    whereUsed: 'Objects and emotions.',
    tenses: 'Adverb: fragile (rare)',
    synonyms: ['delicate', 'weak', 'brittle'],
  },
  {
    day: 72,
    word: 'Gradual',
    phonetic: '/ˈɡrædʒuəl/',
    partOfSpeech: 'adjective',
    meaning: 'Happening slowly over time.',
    example: 'Gradual progress is still progress.',
    whereUsed: 'Change and improvement.',
    tenses: 'Adverb: gradually',
    synonyms: ['slow', 'steady', 'progressive'],
  },
  {
    day: 73,
    word: 'Harmony',
    phonetic: '/ˈhɑːməni/',
    partOfSpeech: 'noun',
    meaning: 'A pleasing combination or peaceful balance.',
    example: 'Group chat works best in harmony.',
    whereUsed: 'Music, teams, and relationships.',
    tenses: 'Adjective: harmonious',
    synonyms: ['balance', 'unity', 'accord'],
  },
  {
    day: 74,
    word: 'Illuminate',
    phonetic: '/ɪˈluːmɪneɪt/',
    partOfSpeech: 'verb',
    meaning: 'To light up or make clear.',
    example: 'This example illuminates the meaning.',
    whereUsed: 'Formal and academic tone.',
    tenses: 'Past: illuminated',
    synonyms: ['clarify', 'explain', 'light up'],
  },
  {
    day: 75,
    word: 'Jeopardy',
    phonetic: '/ˈdʒepədi/',
    partOfSpeech: 'noun',
    meaning: 'Risk of harm or failure.',
    example: 'Skipping practice puts goals in jeopardy.',
    whereUsed: 'News and formal speech.',
    tenses: 'Phrase: in jeopardy',
    synonyms: ['danger', 'risk', 'threat'],
  },
  {
    day: 76,
    word: 'Keenly',
    phonetic: '/ˈkiːnli/',
    partOfSpeech: 'adverb',
    meaning: 'In an eager or intense way.',
    example: 'She keenly listens to native speakers.',
    whereUsed: 'Advanced descriptions.',
    tenses: 'From adjective: keen',
    synonyms: ['eagerly', 'intensely', 'sharply'],
  },
  {
    day: 77,
    word: 'Luminous',
    phonetic: '/ˈluːmɪnəs/',
    partOfSpeech: 'adjective',
    meaning: 'Giving off light; bright and clear.',
    example: 'Her explanation was luminous and simple.',
    whereUsed: 'Poetic descriptions.',
    tenses: 'Noun: luminosity',
    synonyms: ['bright', 'radiant', 'glowing'],
  },
  {
    day: 78,
    word: 'Magnitude',
    phonetic: '/ˈmæɡnɪtjuːd/',
    partOfSpeech: 'noun',
    meaning: 'The great size or importance of something.',
    example: 'Understand the magnitude of daily practice.',
    whereUsed: 'Science and formal writing.',
    tenses: 'Related: magnificent',
    synonyms: ['scale', 'size', 'importance'],
  },
  {
    day: 79,
    word: 'Notable',
    phonetic: '/ˈnəʊtəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Important and worth noticing.',
    example: 'A notable change in her accent.',
    whereUsed: 'News and reports.',
    tenses: 'Adverb: notably',
    synonyms: ['remarkable', 'significant', 'noteworthy'],
  },
  {
    day: 80,
    word: 'Outspoken',
    phonetic: '/aʊtˈspəʊkən/',
    partOfSpeech: 'adjective',
    meaning: 'Expressing opinions openly and boldly.',
    example: 'Outspoken learners ask more questions.',
    whereUsed: 'Personality and politics.',
    tenses: 'From phrasal verb: speak out',
    synonyms: ['bold', 'frank', 'direct'],
  },
  {
    day: 81,
    word: 'Profound',
    phonetic: '/prəˈfaʊnd/',
    partOfSpeech: 'adjective',
    meaning: 'Very deep or intense.',
    example: 'Language opens profound opportunities.',
    whereUsed: 'Philosophy and formal essays.',
    tenses: 'Adverb: profoundly',
    synonyms: ['deep', 'intense', 'great'],
  },
  {
    day: 82,
    word: 'Quaint',
    phonetic: '/kweɪnt/',
    partOfSpeech: 'adjective',
    meaning: 'Attractively old-fashioned or charming.',
    example: 'We met in a quaint café to practice.',
    whereUsed: 'Travel and storytelling.',
    tenses: 'Adverb: quaintly',
    synonyms: ['charming', 'picturesque', 'old-fashioned'],
  },
  {
    day: 83,
    word: 'Resilient',
    phonetic: '/rɪˈzɪliənt/',
    partOfSpeech: 'adjective',
    meaning: 'Able to recover quickly from difficulty.',
    example: 'Resilient learners keep going.',
    whereUsed: 'Psychology and coaching.',
    tenses: 'Noun: resilience',
    synonyms: ['tough', 'strong', 'flexible'],
  },
  {
    day: 84,
    word: 'Subtle',
    phonetic: '/ˈsʌtəl/',
    partOfSpeech: 'adjective',
    meaning: 'Not obvious; delicate and hard to notice.',
    example: 'Notice subtle differences in tone.',
    whereUsed: 'Art, humor, and advanced English.',
    tenses: 'Adverb: subtly',
    synonyms: ['slight', 'faint', 'nuanced'],
  },
  {
    day: 85,
    word: 'Tangible',
    phonetic: '/ˈtændʒəbəl/',
    partOfSpeech: 'adjective',
    meaning: 'Clear and real enough to touch or measure.',
    example: 'Set tangible weekly goals.',
    whereUsed: 'Business and planning.',
    tenses: 'Opposite: intangible',
    synonyms: ['real', 'concrete', 'measurable'],
  },
  {
    day: 86,
    word: 'Unite',
    phonetic: '/juˈnaɪt/',
    partOfSpeech: 'verb',
    meaning: 'To join together for a common purpose.',
    example: 'Apps unite learners across regions.',
    whereUsed: 'Teams, countries, and causes.',
    tenses: 'Past: united',
    synonyms: ['join', 'combine', 'merge'],
  },
  {
    day: 87,
    word: 'Versatile',
    phonetic: '/ˈvɜːsətaɪl/',
    partOfSpeech: 'adjective',
    meaning: 'Able to do many things well.',
    example: 'English is a versatile global tool.',
    whereUsed: 'Skills and tools.',
    tenses: 'Noun: versatility',
    synonyms: ['flexible', 'adaptable', 'all-round'],
  },
  {
    day: 88,
    word: 'Widespread',
    phonetic: '/ˈwaɪdspred/',
    partOfSpeech: 'adjective',
    meaning: 'Found in many places or among many people.',
    example: 'English is widespread worldwide.',
    whereUsed: 'News and reports.',
    tenses: 'From: wide + spread',
    synonyms: ['common', 'extensive', 'prevalent'],
  },
  {
    day: 89,
    word: 'Yearly',
    phonetic: '/ˈjɪəli/',
    partOfSpeech: 'adjective / adverb',
    meaning: 'Happening every year.',
    example: 'A yearly review tracks your level.',
    whereUsed: 'Plans and finance.',
    tenses: 'Noun: year',
    synonyms: ['annual', 'once a year'],
  },
  {
    day: 90,
    word: 'Zeal',
    phonetic: '/ziːl/',
    partOfSpeech: 'noun',
    meaning: 'Great enthusiasm for a cause.',
    example: 'She studies with zeal.',
    whereUsed: 'Formal and literary use.',
    tenses: 'Adjective: zealous',
    synonyms: ['passion', 'enthusiasm', 'devotion'],
  },
  {
    day: 91,
    word: 'Articulate',
    phonetic: '/ɑːˈtɪkjuleɪt/',
    partOfSpeech: 'verb / adjective',
    meaning: 'To express ideas clearly; well-spoken.',
    example: 'He articulates his thoughts well.',
    whereUsed: 'Presentations and interviews.',
    tenses: 'Past: articulated',
    synonyms: ['express', 'communicate', 'eloquent'],
  },
  {
    day: 92,
    word: 'Benchmark',
    phonetic: '/ˈbentʃmɑːk/',
    partOfSpeech: 'noun',
    meaning: 'A standard used for comparison.',
    example: 'Use day one as your benchmark.',
    whereUsed: 'Business and testing.',
    tenses: 'Verb: benchmark',
    synonyms: ['standard', 'reference', 'measure'],
  },
  {
    day: 93,
    word: 'Candid',
    phonetic: '/ˈkændɪd/',
    partOfSpeech: 'adjective',
    meaning: 'Honest and direct, even if uncomfortable.',
    example: 'Give candid feedback kindly.',
    whereUsed: 'Reviews and coaching.',
    tenses: 'Adverb: candidly',
    synonyms: ['frank', 'open', 'blunt'],
  },
  {
    day: 94,
    word: 'Diligent',
    phonetic: '/ˈdɪlɪdʒənt/',
    partOfSpeech: 'adjective',
    meaning: 'Careful and hardworking.',
    example: 'Diligent learners finish 100 days.',
    whereUsed: 'School and workplace.',
    tenses: 'Noun: diligence',
    synonyms: ['hardworking', 'careful', 'thorough'],
  },
  {
    day: 95,
    word: 'Empathy',
    phonetic: '/ˈempəθi/',
    partOfSpeech: 'noun',
    meaning: 'Understanding another person’s feelings.',
    example: 'Empathy improves conversation.',
    whereUsed: 'Relationships and support.',
    tenses: 'Adjective: empathetic',
    synonyms: ['understanding', 'compassion', 'sympathy'],
  },
  {
    day: 96,
    word: 'Frugal',
    phonetic: '/ˈfruːɡəl/',
    partOfSpeech: 'adjective',
    meaning: 'Careful with money; not wasteful.',
    example: 'Frugal students use free tools.',
    whereUsed: 'Money and lifestyle.',
    tenses: 'Adverb: frugally',
    synonyms: ['thrifty', 'economical', 'saving'],
  },
  {
    day: 97,
    word: 'Gregarious',
    phonetic: '/ɡrɪˈɡeəriəs/',
    partOfSpeech: 'adjective',
    meaning: 'Sociable; enjoying company.',
    example: 'Gregarious learners love group chat.',
    whereUsed: 'Personality descriptions.',
    tenses: 'Noun: gregariousness (rare)',
    synonyms: ['sociable', 'outgoing', 'friendly'],
  },
  {
    day: 98,
    word: 'Habit',
    phonetic: '/ˈhæbɪt/',
    partOfSpeech: 'noun',
    meaning: 'A regular action done almost without thinking.',
    example: 'Build a daily word habit.',
    whereUsed: 'Self-improvement (key topic).',
    tenses: 'Adjective: habitual',
    synonyms: ['routine', 'practice', 'custom'],
  },
  {
    day: 99,
    word: 'Insight',
    phonetic: '/ˈɪnsaɪt/',
    partOfSpeech: 'noun',
    meaning: 'A deep and clear understanding.',
    example: 'This word gives insight into formal English.',
    whereUsed: 'Analysis and learning.',
    tenses: 'Plural: insights',
    synonyms: ['understanding', 'wisdom', 'perception'],
  },
  {
    day: 100,
    word: 'Judicious',
    phonetic: '/dʒuːˈdɪʃəs/',
    partOfSpeech: 'adjective',
    meaning: 'Showing good judgment.',
    example: 'Make judicious use of new vocabulary.',
    whereUsed: 'Formal advice.',
    tenses: 'Adverb: judiciously',
    synonyms: ['wise', 'sensible', 'prudent'],
  },
  {
    day: 101,
    word: 'Knack',
    phonetic: '/næk/',
    partOfSpeech: 'noun',
    meaning: 'A natural skill for doing something.',
    example: 'She has a knack for idioms.',
    whereUsed: 'Informal compliments.',
    tenses: 'Plural: knacks',
    synonyms: ['talent', 'skill', 'gift'],
  },
  {
    day: 102,
    word: 'Lucid',
    phonetic: '/ˈluːsɪd/',
    partOfSpeech: 'adjective',
    meaning: 'Clear and easy to understand.',
    example: 'Give a lucid explanation.',
    whereUsed: 'Writing and teaching.',
    tenses: 'Adverb: lucidly',
    synonyms: ['clear', 'plain', 'coherent'],
  },
  {
    day: 103,
    word: 'Meticulous',
    phonetic: '/məˈtɪkjələs/',
    partOfSpeech: 'adjective',
    meaning: 'Very careful about every small detail.',
    example: 'Meticulous notes help review words.',
    whereUsed: 'Work quality.',
    tenses: 'Adverb: meticulously',
    synonyms: ['careful', 'precise', 'thorough'],
  },
  {
    day: 104,
    word: 'Nuance',
    phonetic: '/ˈnjuːɑːns/',
    partOfSpeech: 'noun',
    meaning: 'A small difference in meaning or tone.',
    example: 'Learn the nuance between similar words.',
    whereUsed: 'Advanced English.',
    tenses: 'Adjective: nuanced',
    synonyms: ['shade', 'subtlety', 'distinction'],
  },
  {
    day: 105,
    word: 'Pragmatic',
    phonetic: '/præɡˈmætɪk/',
    partOfSpeech: 'adjective',
    meaning: 'Focused on practical results.',
    example: 'Take a pragmatic approach to grammar.',
    whereUsed: 'Business and problem solving.',
    tenses: 'Adverb: pragmatically',
    synonyms: ['practical', 'realistic', 'sensible'],
  },
  {
    day: 106,
    word: 'Quell',
    phonetic: '/kwel/',
    partOfSpeech: 'verb',
    meaning: 'To stop or calm something strong.',
    example: 'Deep breaths quell speaking anxiety.',
    whereUsed: 'Literary and formal.',
    tenses: 'Past: quelled',
    synonyms: ['calm', 'suppress', 'ease'],
  },
  {
    day: 107,
    word: 'Rhetoric',
    phonetic: '/ˈretərɪk/',
    partOfSpeech: 'noun',
    meaning: 'The art of persuasive speaking.',
    example: 'Politicians use rhetoric skillfully.',
    whereUsed: 'Academic and media.',
    tenses: 'Adjective: rhetorical',
    synonyms: ['oratory', 'persuasion', 'speechcraft'],
  },
  {
    day: 108,
    word: 'Scrutiny',
    phonetic: '/ˈskruːtɪni/',
    partOfSpeech: 'noun',
    meaning: 'Close and critical examination.',
    example: 'Your essay faced public scrutiny.',
    whereUsed: 'News and formal contexts.',
    tenses: 'Verb: scrutinize',
    synonyms: ['examination', 'inspection', 'review'],
  },
  {
    day: 109,
    word: 'Tenacious',
    phonetic: '/təˈneɪʃəs/',
    partOfSpeech: 'adjective',
    meaning: 'Not giving up easily.',
    example: 'Tenacious practice wins fluency.',
    whereUsed: 'Motivation and sports.',
    tenses: 'Noun: tenacity',
    synonyms: ['persistent', 'determined', 'stubborn'],
  },
  {
    day: 110,
    word: 'Ubiquitous',
    phonetic: '/juːˈbɪkwɪtəs/',
    partOfSpeech: 'adjective',
    meaning: 'Seeming to be everywhere.',
    example: 'Smartphones are ubiquitous.',
    whereUsed: 'Academic and tech writing.',
    tenses: 'Noun: ubiquity',
    synonyms: ['everywhere', 'omnipresent', 'common'],
  },
  {
    day: 111,
    word: 'Venerate',
    phonetic: '/ˈvenəreɪt/',
    partOfSpeech: 'verb',
    meaning: 'To respect deeply, almost worship.',
    example: 'Some cultures venerate great teachers.',
    whereUsed: 'History and religion.',
    tenses: 'Past: venerated',
    synonyms: ['honor', 'revere', 'respect'],
  },
  {
    day: 112,
    word: 'Witty',
    phonetic: '/ˈwɪti/',
    partOfSpeech: 'adjective',
    meaning: 'Clever and funny in speech.',
    example: 'A witty reply keeps chat lively.',
    whereUsed: 'Social conversation.',
    tenses: 'Noun: wit',
    synonyms: ['clever', 'humorous', 'amusing'],
  },
  {
    day: 113,
    word: 'Yearning',
    phonetic: '/ˈjɜːnɪŋ/',
    partOfSpeech: 'noun',
    meaning: 'A strong longing for something.',
    example: 'A yearning to speak without fear.',
    whereUsed: 'Literary tone.',
    tenses: 'From verb: yearn',
    synonyms: ['longing', 'desire', 'craving'],
  },
  {
    day: 114,
    word: 'Zest',
    phonetic: '/zest/',
    partOfSpeech: 'noun',
    meaning: 'Great enthusiasm and energy.',
    example: 'Study with zest each morning.',
    whereUsed: 'Informal motivation.',
    tenses: 'Adjective: zesty (for food)',
    synonyms: ['enthusiasm', 'energy', 'gusto'],
  }
];

export const DAILY_WORDS: DailyWordEntry[] = DAILY_WORDS_ALL.slice(0, DAILY_WORD_TOTAL_DAYS);

export function getDailyWordDayNumber(): number {
  const epochDay = Math.floor(Date.now() / (1000 * 60 * 60 * 24));
  return (epochDay % DAILY_WORD_TOTAL_DAYS) + 1;
}

export function getDailyWordForToday(): DailyWordEntry {
  const index = getDailyWordDayNumber() - 1;
  return DAILY_WORDS[index];
}
