export const FILL_BLANKS_DATA = [
  { sentence: "She ___ to the market every day.", options: ["go", "goes", "going"], answer: "goes", rule: "Use 'goes' for third-person singular (She/He/It) in the simple present tense." },
  { sentence: "The cat jumped ___ the wall.", options: ["over", "under", "through"], answer: "over", rule: "Use the preposition 'over' when moving across and above something." },
  { sentence: "I have been living here ___ 2015.", options: ["since", "for", "from"], answer: "since", rule: "Use 'since' when referring to a specific starting point in time." },
  { sentence: "They ___ finished their homework yet.", options: ["haven't", "hasn't", "didn't"], answer: "haven't", rule: "The keyword 'yet' with plural 'They' requires present perfect tense 'haven't'." },
  { sentence: "If I ___ a bird, I would fly.", options: ["am", "was", "were"], answer: "were", rule: "In unreal conditional statements (Second Conditional), use 'were' for all subjects." },
  { sentence: "She is the ___ girl in the class.", options: ["smartest", "smarter", "smart"], answer: "smartest", rule: "Use the superlative form '-est' when comparing more than two subject entities." },
  { sentence: "I look forward to ___ you.", options: ["see", "seeing", "saw"], answer: "seeing", rule: "The preposition 'to' here is part of the phrasal verb and must be followed by a gerund (-ing)." },
  { sentence: "Neither of the boys ___ here.", options: ["are", "is", "were"], answer: "is", rule: "'Neither of' takes a singular verb (is) in formal grammar." },
  { sentence: "He drives very ___.", options: ["careful", "carefully", "care"], answer: "carefully", rule: "Use an adverb ending in -ly ('carefully') to modify an action verb ('drives')." },
  { sentence: "By this time next year, I ___ graduated.", options: ["will have", "would have", "will be"], answer: "will have", rule: "Use the future perfect (will have + past participle) for actions guaranteed to be completed before a future time." },
  { sentence: "There are ___ apples left in the basket.", options: ["few", "little", "much"], answer: "few", rule: "Use 'few' for countable plural nouns like 'apples'." },
  { sentence: "The book ___ you gave me is amazing.", options: ["who", "whom", "which"], answer: "which", rule: "Use the relative pronoun 'which' or 'that' for non-human objects." },
  { sentence: "Hardly had I arrived ___ it started to rain.", options: ["than", "when", "then"], answer: "when", rule: "'Hardly' pairs perfectly with 'when' in past perfect sequence inversions." },
  { sentence: "You had better ___ a doctor.", options: ["to see", "see", "seeing"], answer: "see", rule: "'Had better' is a modal auxiliary phrase followed by the bare infinitive (without 'to')." },
  { sentence: "Let ___ go to the park.", options: ["we", "us", "our"], answer: "us", rule: "'Let' takes an object pronoun (us, me, him) directly after it." },
  { sentence: "I am used to ___ up early.", options: ["wake", "waking", "woke"], answer: "waking", rule: "'Used to' acting as an adjective phrase is followed by a gerund (-ing)." },
  { sentence: "___ he was tired, he kept working.", options: ["Because", "Although", "However"], answer: "Although", rule: "'Although' is used to introduce a contrasting dependent clause." },
  { sentence: "He told me that he ___ finish the report.", options: ["will", "would", "can"], answer: "would", rule: "When reporting past speech, 'will' becomes 'would'." },
  { sentence: "The team ___ playing very well today.", options: ["is", "are", "were"], answer: "is", rule: "Collective nouns acting as a single unit take a singular verb." },
  { sentence: "She ___ the piano since she was five.", options: ["plays", "is playing", "has been playing"], answer: "has been playing", rule: "Action starting in the past and continuing now uses present perfect continuous." },
  { sentence: "I prefer tea ___ coffee.", options: ["to", "than", "rather"], answer: "to", rule: "The verb 'prefer' is idiomatically followed by 'to'." },
  { sentence: "Scarcely had she entered ___ the phone rang.", options: ["than", "when", "while"], answer: "when", rule: "'Scarcely' pairs with 'when' for immediate sequencing of past actions." },
  { sentence: "Not only ___ he late, but he also forgot the file.", options: ["was", "is", "did"], answer: "was", rule: "When 'Not only' starts a sentence, it requires subject-auxiliary inversion." },
  { sentence: "The news ___ not good today.", options: ["are", "is", "were"], answer: "is", rule: "'News' is an uncountable noun and always takes a singular verb." },
  { sentence: "You ___ not worry about it.", options: ["must", "need", "ought"], answer: "need", rule: "'Need not' (needn't) is used to express lack of obligation." },
  { sentence: "I have ___ idea what you mean.", options: ["no", "not", "none"], answer: "no", rule: "'No' acts as an adjective modifying a noun (idea)." },
  { sentence: "We will go as soon as he ___.", options: ["will arrive", "arrives", "arrived"], answer: "arrives", rule: "In time clauses referring to the future, use the present simple tense (arrives)." },
  { sentence: "He resembles ___ his father.", options: ["to", "with", "no preposition"], answer: "no preposition", rule: "The verb 'resemble' is transitive and takes a direct object without a preposition." },
  { sentence: "I wish I ___ a million dollars.", options: ["have", "had", "will have"], answer: "had", rule: "Use past tense 'had' after 'wish' for present unreal desires." },
  { sentence: "This is the house ___ Jack built.", options: ["who", "that", "whom"], answer: "that", rule: "Use 'that' to introduce a restrictive relative clause for objects." },
  { sentence: "Every student ___ expected to attend.", options: ["is", "are", "were"], answer: "is", rule: "'Every' makes the subject singular, requiring a singular verb." },
  { sentence: "I asked him where ___ going.", options: ["was he", "he was", "is he"], answer: "he was", rule: "Indirect questions use affirmative word order (subject + verb)." },
  { sentence: "She objected to ___ treated like a child.", options: ["be", "being", "been"], answer: "being", rule: "The preposition 'to' requires a gerund ('being')." },
  { sentence: "It is important that he ___ on time.", options: ["be", "is", "are"], answer: "be", rule: "Use the subjunctive 'be' after expressions of importance or necessity." },
  { sentence: "Are you accustomed to ___ spicy food?", options: ["eat", "eating", "ate"], answer: "eating", rule: "'Accustomed to' must be followed by a noun or gerund." },
  { sentence: "I would rather you ___ tomorrow.", options: ["come", "came", "will come"], answer: "came", rule: "'Would rather + subject' takes the past tense for a present/future preference." },
  { sentence: "The scissors ___ on the table.", options: ["is", "are", "was"], answer: "are", rule: "'Scissors' is a plural noun and takes a plural verb." },
  { sentence: "He denied ___ the money.", options: ["stealing", "to steal", "steal"], answer: "stealing", rule: "The verb 'deny' is followed by a gerund." },
  { sentence: "I congratulate you ___ your success.", options: ["for", "on", "about"], answer: "on", rule: "The verb 'congratulate' takes the preposition 'on'." },
  { sentence: "___ of the two sisters is married.", options: ["Both", "Neither", "All"], answer: "Neither", rule: "'Neither' is used when referring to two people negatively." },
  { sentence: "My friend and ___ went to the store.", options: ["I", "me", "myself"], answer: "I", rule: "'I' is a subject pronoun; it forms a compound subject with 'My friend'." },
  { sentence: "He is good ___ math.", options: ["in", "at", "with"], answer: "at", rule: "The adjective 'good' indicating skill takes the preposition 'at'." },
  { sentence: "The car ___ down on my way to work.", options: ["broke", "break", "broken"], answer: "broke", rule: "'Broke down' is the simple past of the phrasal verb meaning to stop working." },
  { sentence: "She ___ the room before I arrived.", options: ["left", "has left", "had left"], answer: "had left", rule: "Use past perfect (had left) for an action completed before another past action." },
  { sentence: "Would you mind ___ the window?", options: ["open", "opening", "to open"], answer: "opening", rule: "The phrase 'would you mind' is strictly followed by a gerund (-ing)." },
  { sentence: "Don't rely ___ him.", options: ["in", "on", "for"], answer: "on", rule: "The verb 'rely' pairs with the preposition 'on'." },
  { sentence: "I enjoyed ___ the movie last night.", options: ["watching", "to watch", "watch"], answer: "watching", rule: "The verb 'enjoy' is always followed by a gerund." },
  { sentence: "He is capable ___ doing better.", options: ["of", "to", "in"], answer: "of", rule: "The adjective 'capable' takes the preposition 'of + gerund'." },
  { sentence: "We discussed ___ the matter for hours.", options: ["about", "on", "no preposition"], answer: "no preposition", rule: "'Discuss' is transitive and does not take a preposition like 'about'." },
  { sentence: "She is married ___ a doctor.", options: ["with", "to", "by"], answer: "to", rule: "The correct preposition after 'married' is 'to'." },
  { sentence: "He prevented me ___ going.", options: ["to", "from", "for"], answer: "from", rule: "'Prevent' is followed by 'from' plus a gerund." },
  { sentence: "This ring is made ___ gold.", options: ["of", "from", "with"], answer: "of", rule: "Use 'made of' when the material (gold) does not change its basic nature." },
  { sentence: "Bread is made ___ flour.", options: ["of", "from", "with"], answer: "from", rule: "Use 'made from' when the material undergoes a substantial change." },
  { sentence: "It has been raining ___ morning.", options: ["since", "for", "from"], answer: "since", rule: "Use 'since' for a continuous action starting at a specific point in the past." },
  { sentence: "I differ ___ you on this point.", options: ["from", "with", "to"], answer: "with", rule: "Use 'differ with' when disagreeing with a person's opinion." },
  { sentence: "His idea differs ___ mine.", options: ["from", "with", "to"], answer: "from", rule: "Use 'differ from' when comparing unlike things or ideas." },
  { sentence: "You are prohibited ___ entering.", options: ["to", "from", "against"], answer: "from", rule: "'Prohibit' takes the preposition 'from' plus a gerund." },
  { sentence: "She parted ___ her parents in tears.", options: ["with", "from", "of"], answer: "from", rule: "Use 'part from' when referring to separating from a person." },
  { sentence: "He parted ___ his money reluctantly.", options: ["with", "from", "of"], answer: "with", rule: "Use 'part with' when referring to relinquishing an object or possession." },
  { sentence: "I insist ___ your coming.", options: ["on", "for", "to"], answer: "on", rule: "The verb 'insist' is followed by the preposition 'on'." },
  { sentence: "They are proud ___ their heritage.", options: ["for", "of", "about"], answer: "of", rule: "The adjective 'proud' pairs with the preposition 'of'." },
  { sentence: "I am fond ___ listening to music.", options: ["of", "to", "in"], answer: "of", rule: "The adjective 'fond' pairs with the preposition 'of'." },
  { sentence: "He is addicted ___ smoking.", options: ["with", "to", "in"], answer: "to", rule: "The adjective 'addicted' takes the preposition 'to'." },
  { sentence: "Beware ___ dogs.", options: ["from", "of", "with"], answer: "of", rule: "The warning 'beware' pairs with the preposition 'of'." },
  { sentence: "This book belongs ___ me.", options: ["for", "to", "with"], answer: "to", rule: "The verb 'belong' takes the preposition 'to' to denote ownership." },
  { sentence: "He is afraid ___ spiders.", options: ["from", "of", "with"], answer: "of", rule: "The adjective 'afraid' pairs with the preposition 'of'." },
  { sentence: "I agree ___ your proposal.", options: ["with", "to", "on"], answer: "to", rule: "Use 'agree to' when consenting to an idea, plan, or proposal." },
  { sentence: "I agree ___ you.", options: [ "with", "to", "on" ], answer: "with", rule: "Use 'agree with' when referring to sharing an opinion with a person." },
  { sentence: "It is time he ___ home.", options: ["goes", "went", "will go"], answer: "went", rule: "'It is time' + subject triggers the past tense to indicate present urgency." },
  { sentence: "I am looking forward to ___ you.", options: ["meet", "meeting", "have met"], answer: "meeting", rule: "'Look forward to' is followed by a gerund." },
  { sentence: "He made me ___.", options: ["cry", "to cry", "crying"], answer: "cry", rule: "The causative verb 'make' is followed by a bare infinitive." },
  { sentence: "Let him ___ what he wants.", options: ["do", "to do", "doing"], answer: "do", rule: "'Let' is followed by an object and a bare infinitive." },
  { sentence: "___ a beautiful day!", options: ["What", "How", "Which"], answer: "What", rule: "Use 'What a' before an adjective + singular countable noun." },
  { sentence: "___ beautiful the day is!", options: ["What", "How", "Which"], answer: "How", rule: "Use 'How' directly before an adjective in an exclamatory sentence." },
  { sentence: "He is the man ___ I met yesterday.", options: ["who", "whom", "whose"], answer: "whom", rule: "'Whom' is the correct object pronoun relative to 'I met'." },
  { sentence: "This is the house ___ roof was damaged.", options: ["who's", "which", "whose"], answer: "whose", rule: "'Whose' serves as a possessive relative pronoun for inanimate objects." },
  { sentence: "I don't know ___ he is.", options: ["who", "whom", "which"], answer: "who", rule: "'Who' acts as the subject complement in the noun clause." },
  { sentence: "___ of you can answer the question?", options: ["Who", "Which", "What"], answer: "Which", rule: "Use 'Which' when asking about a specific choice from a limited group." },
  { sentence: "He acts as if he ___ the boss.", options: ["is", "was", "were"], answer: "were", rule: "'As if' introduces an unreal situation, requiring the subjunctive 'were'." },
  { sentence: "No sooner had he left ___ it started raining.", options: ["than", "when", "then"], answer: "than", rule: "'No sooner' strictly pairs with 'than' to sequence two immediate past events." },
  { sentence: "The number of students ___ increasing.", options: ["is", "are", "were"], answer: "is", rule: "'The number of' specifies a singular quantity and takes a singular verb." },
  { sentence: "A number of students ___ present.", options: ["is", "are", "was"], answer: "are", rule: "'A number of' means 'several' and takes a plural verb." },
  { sentence: "Physics ___ a difficult subject.", options: ["is", "are", "were"], answer: "is", rule: "'Physics', despite ending in -s, is a singular subject category." },
  { sentence: "One of the boys ___ missing.", options: ["is", "are", "were"], answer: "is", rule: "'One of' makes the subject 'One', which requires a singular verb." },
  { sentence: "Fifty dollars ___ a lot of money.", options: ["is", "are", "were"], answer: "is", rule: "Amounts of money, time, or distance are treated as singular units." },
  { sentence: "The committee ___ issued its report.", options: ["has", "have", "are"], answer: "has", rule: "A collective noun acting as a single entity takes a singular verb." },
  { sentence: "He as well as his friends ___ invited.", options: ["is", "are", "were"], answer: "is", rule: "Phrases like 'as well as' don't change the number of the first subject (He is)." },
  { sentence: "Either he or I ___ mistaken.", options: ["is", "are", "am"], answer: "am", rule: "In 'either/or', the verb agrees with the subject closest to it (I am)." },
  { sentence: "Not only the teacher but also the students ___ laughing.", options: ["was", "were", "is"], answer: "were", rule: "With 'not only/but also', the verb agrees with the nearest subject (students were)." },
  { sentence: "Many a man ___ tried it.", options: ["has", "have", "are"], answer: "has", rule: "The traditional idiom 'many a' is followed by a singular noun and verb." },
  { sentence: "More than one person ___ injured.", options: ["was", "were", "are"], answer: "was", rule: "Despite its meaning, 'More than one' takes a singular verb in formal English." },
  { sentence: "He prefers reading ___ writing.", options: ["to", "than", "over"], answer: "to", rule: "'Prefer' + gerund is followed by 'to' + gerund." },
  { sentence: "She ran fast lest she ___ miss the train.", options: ["would", "should", "might"], answer: "should", rule: "'Lest' is traditionally followed by the modal verb 'should'." },
  { sentence: "Although he is rich, ___ he is humble.", options: ["but", "yet", "and"], answer: "yet", rule: "'Although' introduces a concession; its traditional correlative is 'yet' or a comma." },
  { sentence: "He has been working here ___ two years.", options: ["since", "for", "from"], answer: "for", rule: "Use 'for' to specify a duration or period of time." },
  { sentence: "I will wait until he ___.", options: ["returns", "will return", "returned"], answer: "returns", rule: "Do not use future tense directly after time words like 'until'." },
  { sentence: "If you ___, you would have passed.", options: ["studied", "had studied", "study"], answer: "had studied", rule: "Third conditional unreal past requires past perfect in the 'if' clause." },
  { sentence: "It is necessary that he ___ informed.", options: ["be", "is", "are"], answer: "be", rule: "Adjectives of necessity strictly require the subjunctive 'be'." },
  { sentence: "I demand that he ___ apology.", options: ["makes", "make", "made"], answer: "make", rule: "Verbs of demanding trigger the subjunctive base form 'make'." },
  { sentence: "I suggest he ___ to a doctor.", options: ["goes", "go", "went"], answer: "go", rule: "Verbs of suggesting trigger the subjective base form without 'to' ('go')." }
];
