/** Auto-generated by frontend/scripts/sync-legal-html.js — do not edit by hand. */
const privacyPolicyHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Ohm's Privacy Policy</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; background: #f8f9fa; color: #1f1f1f; }
    .wrap { max-width: 900px; margin: 0 auto; padding: 24px; }
    h1 { margin: 0 0 8px; font-size: 30px; }
    .meta { color: #5f6368; margin-bottom: 20px; }
    .card { background: #fff; border: 1px solid #e8eaed; border-radius: 12px; padding: 18px; margin-bottom: 14px; }
    h2 { margin: 0 0 8px; font-size: 20px; }
    p { margin: 0; line-height: 1.6; }
    a { color: #c40000; text-decoration: none; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>Ohm's Privacy Policy</h1>
    <div class="meta">Ohm's English Learning — Last updated: 3 June 2026</div>
    <div class="card"><h2>1. Overview</h2><p>This Privacy Policy explains how Ohm's handles information when you use our English learning app on Google Play. Developer contact: aarambhfoundation111@gmail.com.</p></div>
    <div class="card"><h2>2. Information we collect</h2><p>Email and OTP codes; profile (name, phone, region, gender, learning level); learning progress, scores, and rewards; random chat messages; basic server logs for security. We do not sell personal information.</p></div>
    <div class="card"><h2>3. Information we do not collect</h2><p>We do not collect contacts, location, gallery photos/videos, SMS, call logs, advertising ID, or health/financial data.</p></div>
    <div class="card"><h2>4. Camera and microphone</h2><p>Ohm's requests camera/microphone only when you tap to start video or voice practice. Live media is peer-to-peer between learners and is not recorded or stored on our servers. No background access. No photo gallery access.</p></div>
    <div class="card"><h2>5. Random chat and user content</h2><p>Chat messages are visible to matched partners during a session. Optional voice/video practice requires both users to accept. Automated filters apply. Skip or report users from chat or Contact Us. For English practice only — not dating.</p></div>
    <div class="card"><h2>6. How we use information</h2><p>Authentication, courses, games, chat matching, leaderboards, OTP email, support, and safety enforcement. No third-party advertising.</p></div>
    <div class="card"><h2>7. Sharing</h2><p>We share data only with hosting/email processors, when required by law, or for safety. We do not sell personal data.</p></div>
    <div class="card"><h2>8. Security</h2><p>We use reasonable safeguards including encryption in transit (HTTPS / secure chat connections).</p></div>
    <div class="card"><h2>9. Retention</h2><p>Data is kept while your account is active and as needed legally or operationally.</p></div>
    <div class="card"><h2>10. Children</h2><p>Not directed to children under 13. Under-18 users should have parental consent.</p></div>
    <div class="card"><h2>11. Account deletion</h2><p>Delete your account in-app: Contact Us → Delete my account. Or email <a href="mailto:aarambhfoundation111@gmail.com?subject=Account%20deletion%20request">aarambhfoundation111@gmail.com</a> from your registered Gmail. Deletion removes profile, progress, and server data.</p></div>
    <div class="card"><h2>12. Google Play</h2><p>Our Google Play Data safety form matches this policy.</p></div>
    <div class="card"><h2>13. Contact</h2><p>Email: <a href="mailto:aarambhfoundation111@gmail.com">aarambhfoundation111@gmail.com</a><br/>Phone: +91 6204111878<br/><a href="/terms-and-conditions">Terms &amp; Conditions</a></p></div>
  </div>
</body>
</html>
`;

const termsHtml = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Ohm's Terms & Conditions</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; background: #f8f9fa; color: #1f1f1f; }
    .wrap { max-width: 900px; margin: 0 auto; padding: 24px; }
    h1 { margin: 0 0 8px; font-size: 30px; }
    .meta { color: #5f6368; margin-bottom: 20px; }
    .card { background: #fff; border: 1px solid #e8eaed; border-radius: 12px; padding: 18px; margin-bottom: 14px; }
    h2 { margin: 0 0 8px; font-size: 20px; }
    p { margin: 0; line-height: 1.6; }
    a { color: #c40000; text-decoration: none; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>Ohm's Terms & Conditions</h1>
    <div class="meta">Ohm's English Learning — Last updated: 3 June 2026</div>
    <div class="card"><h2>1. Acceptance</h2><p>By using Ohm's you agree to these Terms and Google Play policies when installed from Google Play.</p></div>
    <div class="card"><h2>2. Eligibility</h2><p>Minimum age 13. Under-18 users need parental consent.</p></div>
    <div class="card"><h2>3. Service</h2><p>English courses, games, rewards, leaderboards, random chat for practice, and support. Educational use — not dating.</p></div>
    <div class="card"><h2>4. Accounts</h2><p>Gmail + OTP sign-in. You may delete your account from Contact Us.</p></div>
    <div class="card"><h2>5. User conduct</h2><p>No harassment, illegal content, spam, or misuse of chat. English practice only.</p></div>
    <div class="card"><h2>6. User-generated content</h2><p>You are responsible for chat content. We may filter, remove content, or suspend accounts per Google Play UGC policies.</p></div>
    <div class="card"><h2>6a. Reporting</h2><p>Skip partners, use the report button in chat, or contact aarambhfoundation111@gmail.com.</p></div>
    <div class="card"><h2>6b. Camera and microphone</h2><p>Used only when you start related features. No gallery access.</p></div>
    <div class="card"><h2>7. Privacy</h2><p>See <a href="/privacy-policy">Privacy Policy</a>.</p></div>
    <div class="card"><h2>8. Account deletion</h2><p>Contact Us → Delete my account, or email support from your registered Gmail.</p></div>
    <div class="card"><h2>9. Disclaimer</h2><p>App provided "as is" without warranties.</p></div>
    <div class="card"><h2>10. Contact</h2><p>Email: <a href="mailto:aarambhfoundation111@gmail.com">aarambhfoundation111@gmail.com</a><br/>Phone: +91 6204111878</p></div>
  </div>
</body>
</html>
`;

module.exports = {
  privacyPolicyHtml,
  termsHtml,
};
